### ISSUE TITLE
Using ARM deployments I can deploy a string larger then 1024 characters

### ISSUE THREAD

**Issue by Frankwayne** [azureautomation/automation-packs#21]
Using an ARM deployment of an automation variable I can deploy a string longer than 1024 characters.

The azure portal blocks  strings longer than 1024 so I'm unsure if I should be allowed to do this through the ARM templates

**Comment by jefffanjoy** [comment]
Yes.  The UX has an imposed limit of 1024 characters but the API allows string max which is 2GB if I recall correctly.

**Comment by Frankwayne** [comment]
oh that is really cool, and great news.  Thanks!
