### ISSUE TITLE
Applying the configurationdata on a DSC compliationjob via ARM

### ISSUE THREAD

**Issue by mshorrosh** [azureautomation/automation-packs#8]
Hi 

Is there currently any way to apply a configurationdata configuration to a compilationjob similar to what is available via powershell sdk? This is what I am referring to below:

Start-AzureRmAutomationDscCompilationJob -ResourceGroupName "MyResourceGroup" -AutomationAccountName "MyAutomationAccount" -ConfigurationName "CredentialSample" -ConfigurationData $ConfigData

Thanks,
Matt

**Comment by JAL9302** [comment]
Hi,

Currently this can only be done via PowerShell. Can you post a feedback item on our UserVoice page (https://feedback.azure.com/forums/246290-automation) so we can track this and other customers can vote for it as well?

**Comment by mshorrosh** [comment]
Hi Joe

I have added a post regarding this here https://feedback.azure.com/forums/246290-automation/suggestions/11216361-arm-support-for-configurationdata-in-dsc-compilati

Thanks
